In [1]:
import numpy as np
import pandas as pd
import random
import time

In [2]:
'''np.random.randn(y, 1):
For each layer y (number of neurons in that layer), this generates a column vector of shape (y, 1) with random values sampled from a standard normal distribution (mean = 0, standard deviation = 1).
Each value in this vector represents the initial bias for a neuron in that layer.'''

'''
List comprehension:
The list comprehension [np.random.randn(y, 1) for y in sizes[1:]] iterates over the number of neurons in each layer (excluding the input layer) and creates a bias vector for each layer.
'''
'''
Example:
If sizes = [784, 30, 10] (e.g., for an MNIST network with 784 input neurons, 30 hidden neurons, and 10 output neurons):

sizes[1:] = [30, 10]
self.biases will be a list containing:
A (30, 1) array for the biases of the hidden layer.
A (10, 1) array for the biases of the output layer.
'''

'''
Example:
If sizes = [784, 30, 10] (e.g., for an MNIST network with 784 input neurons, 30 hidden neurons, and 10 output neurons):

sizes[:-1] = [784, 30] (input and hidden layers).
sizes[1:] = [30, 10] (hidden and output layers).
zip(sizes[:-1], sizes[1:]) = [(784, 30), (30, 10)].
The resulting self.weights will be a list containing:

A (30, 784) matrix for the weights connecting the input layer to the hidden layer.
A (10, 30) matrix for the weights connecting the hidden layer to the output layer.
'''

"""Train the neural network using mini-batch stochastic gradient descent. The "training_data" is a list of tuples "(x, y)" representing the training inputs and the desired outputs.
If "test_data" is provided then the network will be evaluated against the test data after each epoch, and partial progress printed out.  This is useful for tracking progress, but slows 
things down substantially. The training_data is a list of tuples (x, y) representing the training inputs and corresponding desired outputs."""

"""Update the network's weights and biases by applying gradient descent using backpropagation to a single mini batch. The ``mini_batch`` is a list of tuples ``(x, y)``, and ``eta``
is the learning rate."""

"""Return a tuple ``(nabla_b, nabla_w)`` representing the
gradient for the cost function C_x.  ``nabla_b`` and
``nabla_w`` are layer-by-layer lists of numpy arrays, similar
to ``self.biases`` and ``self.weights``."""

"""Return the number of test inputs for which the neural
network outputs the correct result. Note that the neural
network's output is assumed to be the index of whichever
neuron in the final layer has the highest activation."""

"""Return the vector of partial derivatives \partial C_x /
\partial a for the output activations."""

<>:49: SyntaxWarning: invalid escape sequence '\p'
<>:49: SyntaxWarning: invalid escape sequence '\p'
C:\Users\getch\AppData\Local\Temp\ipykernel_9484\2973414786.py:49: SyntaxWarning: invalid escape sequence '\p'
  """Return the vector of partial derivatives \partial C_x /


'Return the vector of partial derivatives \\partial C_x /\n\\partial a for the output activations.'

The randn function in NumPy (np.random.randn) generates samples from a standard normal distribution (Gaussian distribution) with a mean of 0 and a standard deviation of 1.

In [3]:
train_set, valid_set, test_set = pd.read_pickle("mnist.pkl.gz")

In [4]:
train_set

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], shape=(50000, 784), dtype=float32),
 array([5, 0, 4, ..., 8, 4, 8], shape=(50000,)))

In [5]:
train_x, train_y = train_set

In [6]:
train_x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(50000, 784), dtype=float32)

In [7]:
train_y

array([5, 0, 4, ..., 8, 4, 8], shape=(50000,))

In [8]:
valid_set

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], shape=(10000, 784), dtype=float32),
 array([3, 8, 6, ..., 5, 6, 8], shape=(10000,)))

In [9]:
val_x, val_y = valid_set

In [10]:
val_x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(10000, 784), dtype=float32)

In [11]:
val_y

array([3, 8, 6, ..., 5, 6, 8], shape=(10000,))

In [12]:
test_x, test_y = test_set

In [13]:
test_x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(10000, 784), dtype=float32)

In [14]:
test_y

array([7, 2, 1, ..., 4, 5, 6], shape=(10000,))

In [15]:
import network

net = network.Network([784, 30, 10])
net

sizes: [784, 30, 10], biases: [array([[ 1.81186622],
       [-0.88467413],
       [-0.73143762],
       [-0.54590563],
       [ 0.59132596],
       [-0.7533147 ],
       [ 0.38625414],
       [-0.06141245],
       [-0.35120478],
       [ 0.93933553],
       [ 2.80113522],
       [ 0.13821962],
       [-1.29886672],
       [ 1.7628872 ],
       [-1.85306978],
       [-0.53258631],
       [-0.3599814 ],
       [ 0.81259892],
       [-1.19317314],
       [ 0.28541958],
       [ 1.75939965],
       [-1.03503926],
       [-0.79854113],
       [-1.84973586],
       [-0.16142912],
       [ 0.11145982],
       [ 1.22880326],
       [ 0.03506251],
       [-0.38807249],
       [-0.95799598]]), array([[ 0.15367466],
       [-2.6173999 ],
       [ 1.40997951],
       [-0.80974883],
       [ 0.83759222],
       [ 0.1087377 ],
       [-0.66502291],
       [-1.2597122 ],
       [-0.93731865],
       [ 1.30628165]])], weights: [array([[-1.33860783, -1.50693093,  1.14238679, ..., -0.29714835,
        -

In [16]:
net.SGD(train_x, 30, 10, 3.0, test_data=test_x)

ValueError: too many values to unpack (expected 2)